### ISSUE TITLE
communicate

### ISSUE THREAD

**Issue by keaixiaovv** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#10]
Do you think there is any innovation in scene classification? 
Is it convenient to add a wechat to communicate? My wechat is vv19970403

**Comment by ZhengyuZhao** [comment]
> Do you think there is any innovation in scene classification?
> Is it convenient to add a wechat to communicate? My wechat is vv19970403

I am sorry that I have not followed the new papers in this field since I changed my topic after this publication in 2018. Based on my (out-of-date) experiences, recognizing the scenes in 2D images is not a challenging problem anymore. I can see more new studies done on 3D scene recognition or more fine-grained tasks, such as scene parsing and scene graph generation.
