### ISSUE TITLE
how to get scene recognition result on a single image?

### ISSUE THREAD

**Issue by BillLZD** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#4]
The demo.py can not get the result.

**Comment by ZhengyuZhao** [comment]
> The demo.py can not get the result.
Hi, the demo.py is used for generating the image representation, which integrated multi-scale information. In order to get the final recognition results (accuracy over the dataset), you need to use the extracted features to train a classifier (e.g., SVM in this paper). You can follow other .py scripts to get the final results.

**Comment by ZhengyuZhao** [comment]
Hi, the demo.py is used to extract the image features, which integrate multi-scale information. In order to get the recognition results (accuracy) over the dataset, you need to use the extracted features to train a classifier (here we use SVM). You can follow other .py scripts to do it.

**Comment by ZhengyuZhao** [comment]
> The demo.py can not get the result.

Hi, the demo.py is used to extract the image features, which integrate multi-scale information. In order to get the recognition results (accuracy) over the dataset, you need to use the extracted features to train a classifier (here we use SVM). You can follow other .py scripts to do it.
